### ISSUE TITLE
Incorrect postgresql syntax <migration-id-list>

### ISSUE THREAD

**Issue by hyblerm** [lmc-eu/applyalter#8]
Migration id list tag has incorrect syntax when applied against posgresql.
Seems to be db2 syntax.

Fails with:
`[2016-02-29 08:41:31.472] creating temporary table session.MGR_IDS
[2016-02-29 08:41:31.475] creating temporary table by query: DECLARE GLOBAL TEMPORARY TABLE session.MGR_IDS AS (select id from jd.document) DEFINITION ONLY  on commit preserve rows NOT LOGGED on rollback delete rows WITH REPLACE
ch.ips.g2.applyalter.ApplyAlterException: failed to create temporary table session.MGR_IDS: ERROR: syntax error at or near "TEMPORARY"
        at ch.ips.g2.applyalter.MigrationIdList.createTempTable(MigrationIdList.java:142)
        at ch.ips.g2.applyalter.MigrationIdList.execute(MigrationIdList.java:158)
        at ch.ips.g2.applyalter.ApplyAlter.executeStatement(ApplyAlter.java:509)
        at ch.ips.g2.applyalter.ApplyAlter.applySingleAlter(ApplyAlter.java:471)
        at ch.ips.g2.applyalter.ApplyAlter.applyWithoutClosing(ApplyAlter.java:417)
        at ch.ips.g2.applyalter.ApplyAlter.apply(ApplyAlter.java:394)
        at ch.ips.g2.applyalter.ApplyAlter.apply(ApplyAlter.java:305)
        at ch.ips.g2.applyalter.ApplyAlter.main(ApplyAlter.java:773)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "TEMPORARY"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1592)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1327)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:192)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:350)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:304)
        at ch.ips.g2.applyalter.DbUtils.executeUpdate(DbUtils.java:69)
        at ch.ips.g2.applyalter.MigrationIdList.createTempTable(MigrationIdList.java:134)
        ... 7 more`

**Comment by fafejtao** [comment]
Solved by
https://github.com/lmc-eu/applyalter/pull/18
